# Generated by Django 4.2.23 on 2025-08-30 14:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9bab00bf-197f-40d4-8d2b-29e5e155eb3f'), primary_key=True, serialize=False, unique=True),
        ),
    ]
