# Generated by Django 4.2.23 on 2025-08-30 14:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('161ef577-55b2-4e6a-8773-6ece0da12e91'), primary_key=True, serialize=False, unique=True),
        ),
    ]
