# Generated by Django 4.2.23 on 2025-08-18 14:45

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='The name of the book', max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/books/')),
                ('category', models.PositiveIntegerField(choices=[(0, 'Science'), (1, 'Historical'), (2, 'True Crime'), (3, 'Romance')])),
                ('abstract', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.IntegerField(default=10)),
                ('count', models.PositiveIntegerField(default=0)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
